image: maven:3.6.3-jdk-8

stages:
    - test

checkstyle:
    stage: test
    script:
        - 'mvn checkstyle:check -Dcheckstyle.config.location=google_checks.xml -Dcheckstyle.violationSeverity=warning'
    allow_failure: false

